# These are supported funding model platforms, thank you for supporting my work

patreon: https://www.patreon.com/cw/Grafittiii
payme: https://payme.hsbc/jlpl22
paypal: paypal.me/Lam4913
More on linktree: https://linktr.ee/grafittiii.uru
